CREATE DATABASE PROJECT;

DROP DATABASE PROJECT

USE PROJECT;

CREATE TRIGGER AuditInsertTriggerSECTIONS
ON SECTIONS
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE SECTIONS'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerSECTIONS
ON SECTIONS
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE SECTIONS'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerUSERS 
ON USERS 
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL  (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE USERS'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerUSERS
ON USERS
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE USERS'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerSTUDENTS
ON STUDENTS
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE STUDENTS'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerSTUDENTS
ON STUDENTS
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE STUDENTS'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerFACULTY
ON FACULTY
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE FACULTY'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerFACULTY
ON FACULTY
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE FACULTY'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerACADEMICOFFICERS 
ON ACADEMICOFFICERS 
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE ACADEMICOFFICERS'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerACADEMICOFFICERS
ON ACADEMICOFFICERS
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE ACADEMICOFFICERS'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerCOURSES
ON COURSES
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE COURSES'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerCOURSES
ON COURSES
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE COURSES'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerFEEDBACK
ON FEEDBACK
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE FEEDBACK'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerFEEDBACK
ON FEEDBACK
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE FEEDBACK'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerMARKS
ON MARKS
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE MARKS'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerMARKS
ON MARKS
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE MARKS'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerGRADES
ON GRADES
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE GRADES'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerGRADES
ON GRADES
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE GRADES'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerSTUDENTRECORD
ON STUDENTRECORD
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE STUDENTRECORD'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerSTUDENTRECORD
ON STUDENTRECORD
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE STUDENTRECORD'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerCOURSETEACHING
ON COURSETEACHING
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE COURSETEACHING'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerCOURSETEACHING
ON COURSETEACHING
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE COURSETEACHING'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerCOURSEMARKSDISTRIBUTION
ON COURSEMARKSDISTRIBUTION
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE COURSEMARKSDISTRIBUTION'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerCOURSEMARKSDISTRIBUTION
ON COURSEMARKSDISTRIBUTION
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE COURSEMARKSDISTRIBUTION'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerLOGINDETAILS
ON LOGINDETAILS
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE LOGINDETAILS'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerLOGINDETAILS
ON LOGINDETAILS
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE LOGINDETAILS'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerATTENDANCE
ON ATTENDANCE
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE ATTENDANCE'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerATTENDANCE
ON ATTENDANCE
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE ATTENDANCE'
    FROM deleted
END
GO

CREATE TRIGGER AuditInsertTriggerCOURSETAKING
ON COURSETAKING
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'INSERT INTO TABLE COURSETAKING'
    FROM inserted
END
GO

CREATE TRIGGER AuditDeleteTriggerCOURSETAKING
ON COURSETAKING
AFTER DELETE
AS
BEGIN
    INSERT INTO AUDITTRAIL (dateTime, operation)
    SELECT GETDATE(), 'DELET FROM TABLE COURSETAKING'
    FROM deleted
END
GO

DROP TABLE STUDENTRECORD
DROP TABLE GRADES
DROP TABLE FEEDBACK
DROP table ACADEMICOFFICERS
DROP TABLE ATTENDANCE
DROP TABLE AUDITTRAIL
DROP TABLE COURSEMARKSDISTRIBUTION
DROP TABLE COURSETAKING
DROP TABLE COURSETEACHING
DROP TABLE FACULTY
DROP TABLE LOGINDETAILS
DROP TABLE MARKS
DROP TABLE STUDENTS
DROP TABLE SECTIONS
DROP TABLE USERS
DROP TABLE COURSES

CREATE TABLE SECTIONS
(
	sectionID INT PRIMARY KEY,
	sectionName VARCHAR(1)
)

CREATE TABLE USERS (	
    userID VARCHAR(7) PRIMARY KEY,
    name VARCHAR(20),
    CNIC VARCHAR(20),
    DOB DATE,
    gender VARCHAR(6),
	email VARCHAR(20),
	phone VARCHAR(20),
	address VARCHAR(30),
	campus VARCHAR(10)
)

CREATE TABLE STUDENTS (
    userID VARCHAR(7) PRIMARY KEY,
	degreeProgram VARCHAR(10),
    parentSectionID INT REFERENCES SECTIONS(sectionID),
	program VARCHAR(30),
    FOREIGN KEY (userID) REFERENCES USERS(userID)
)

CREATE TABLE FACULTY (
    userID VARCHAR(7) PRIMARY KEY,
    qualification VARCHAR(100),
    FOREIGN KEY (userID) REFERENCES USERS(userID)
)

CREATE TABLE ACADEMICOFFICERS (
    userID VARCHAR(7) PRIMARY KEY,
    FOREIGN KEY (userID) REFERENCES USERS(userID)
)

CREATE TABLE COURSES
(
	courseCode VARCHAR(6) PRIMARY KEY,
	courseName VARCHAR(30),
	creditHrs INT,
	prerequisite VARCHAR(20),
	electiveAssigned VARCHAR(10),
	semester INT,
	courseCoordinator VARCHAR(20)
)

CREATE TABLE AUDITTRAIL
(
	dateTime DATETIME,
	operation VARCHAR(50),
)

CREATE TABLE FEEDBACK
(
	feedbackID INT PRIMARY KEY,
	studentID VARCHAR(7),
	teacherID VARCHAR(7),
	dateAndTime DATETIME,
	feedbackElement VARCHAR(40),
	elementValue VARCHAR(25),
	FOREIGN KEY (studentID) REFERENCES STUDENTS(userID),
	FOREIGN KEY (teacherID) REFERENCES FACULTY(userID)
)

CREATE TABLE MARKS
(
	studentID VARCHAR(7),
	courseCode VARCHAR(6),
	semester INT,
	obtainedMarks INT,
	totalMarks INT,
	assesmentType VARCHAR(10),

	FOREIGN KEY (studentID) REFERENCES STUDENTS(userID),
	FOREIGN KEY (courseCode) REFERENCES COURSES(courseCode)
)

CREATE TABLE GRADES
(
	grade VARCHAR(2),
	courseCode VARCHAR(6),
	studentID VARCHAR(7),
	FOREIGN KEY (studentID) REFERENCES STUDENTS(userID),
	FOREIGN KEY (courseCode) REFERENCES COURSES(courseCode)
)

CREATE TABLE STUDENTRECORD
(
	studentID VARCHAR(7),
	currentSemester INT,
	creditHrs INT,
	warningCount INT,
	degreeStartYear INT,
	FOREIGN KEY (studentID) REFERENCES STUDENTS(userID)
)

CREATE TABLE COURSETEACHING
(
	courseCode VARCHAR(6),
	teacherID VARCHAR(7),
	sectionID INT,
	FOREIGN KEY (teacherID) REFERENCES FACULTY(userID),
	FOREIGN KEY (courseCode) REFERENCES COURSES(courseCode),
	FOREIGN KEY (sectionID) REFERENCES SECTIONS(sectionID)
)

CREATE TABLE COURSEMARKSDISTRIBUTION
(
    courseCode VARCHAR(6),
    teacherID VARCHAR(7),
    projectWeightage INT,
    quizCount INT,
    quizWeightage INT,
    assignmentCount INT,
    assignmentWeightage INT,
    mid1Weightage INT,
    mid2Weightage INT,
    finalWeightage INT,
    FOREIGN KEY (teacherID) REFERENCES FACULTY(userID),
    FOREIGN KEY (courseCode) REFERENCES COURSES(courseCode),
)

CREATE TABLE LOGINDETAILS
(
	userID VARCHAR(7),
	password varchar(10),
	FOREIGN KEY (userID) REFERENCES USERS(userID)
)

CREATE TABLE ATTENDANCE
(
	lectureNum int,
	studentID VARCHAR(7),
	subjectCode VARCHAR(6),
	statusAttendance VARCHAR(1), /*A FOR ABSENT, P FOR PRESENT, L FOR LATE*/
	duration FLOAT,
	dateAndTime DATETIME
)

CREATE TABLE COURSETAKING
(
	studentID VARCHAR(7),
	courseCode VARCHAR(6),
	sectionID INT,
	active VARCHAR(1),
	semester INT,
    FOREIGN KEY (studentID) REFERENCES STUDENTS(userID),
    FOREIGN KEY (courseCode) REFERENCES COURSES(courseCode)
)

DELETE STUDENTRECORD
DELETE GRADES
DELETE FEEDBACK
DELETE ACADEMICOFFICERS
DELETE ATTENDANCE
DELETE AUDITTRAIL
DELETE COURSEMARKSDISTRIBUTION
DELETE COURSETAKING
DELETE COURSETEACHING
DELETE FACULTY
DELETE LOGINDETAILS
DELETE MARKS
DELETE STUDENTS
DELETE SECTIONS
DELETE USERS
DELETE COURSES	

BULK INSERT SECTIONS FROM 'C:\Users\abuba\OneDrive\Desktop\data\SECTIONS.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT USERS FROM 'C:\Users\abuba\OneDrive\Desktop\data\USERS.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT STUDENTS FROM 'C:\Users\abuba\OneDrive\Desktop\data\STUDENTS.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT FACULTY FROM 'C:\Users\abuba\OneDrive\Desktop\data\FACULTY.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT ACADEMICOFFICERS FROM 'C:\Users\abuba\OneDrive\Desktop\data\ACADEMICOFFICERS.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT STUDENTRECORD FROM 'C:\Users\abuba\OneDrive\Desktop\data\STUDENTRECORD.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT LOGINDETAILS FROM 'C:\Users\abuba\OneDrive\Desktop\data\LOGINDETAILS.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT COURSES FROM 'C:\Users\abuba\OneDrive\Desktop\data\COURSES.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT FEEDBACK FROM 'C:\Users\abuba\OneDrive\Desktop\data\FEEDBACK.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT MARKS FROM 'C:\Users\abuba\OneDrive\Desktop\data\MARKS.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT GRADES FROM 'C:\Users\abuba\OneDrive\Desktop\data\GRADES.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT COURSETEACHING FROM 'C:\Users\abuba\OneDrive\Desktop\data\COURSETEACHING.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT COURSEMARKSDISTRIBUTION FROM 'C:\Users\abuba\OneDrive\Desktop\data\COURSEMARKSDISTRIBUTION.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT ATTENDANCE FROM 'C:\Users\abuba\OneDrive\Desktop\data\ATTENDANCE.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);

BULK INSERT COURSETAKING FROM 'C:\Users\abuba\OneDrive\Desktop\data\COURSETAKING.CSV'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);